version: '3.6'

services:
  jwks-rotator:
    image: porisey/orkeystore:latest
    ports:
      - '4000:3000'
    volumes:
      - /tmp/jwk-db:/tmp/jwk-db
    environment:
      ADMIN_PASSWORD: 'password'
      DATABASE_PATH: '/tmp/jwk-db/jwk.db'
      KEYS_HOST: 'http://localhost:3000'
      GENERATE_KEYS: 'hasura:14_days,test:5_weeks'
